export const CANVAS: {w: number; h: number};
export const MARGIN_X: number;
export const CHAPTER_TOP: number;
export const TITLE_TOP: number;
export const TITLE_PX: number;
export const TITLE_BAND: number;
export const MIN_BODY: number;
export const CONTENT: {x: number; y: number; right: number; bottom: number};
export const RESERVE: {x: number; y: number};
export const AVATAR_D: number;
export const AVATAR_RIGHT: number;
export const AVATAR_BOTTOM: number;
export const AVATAR: {x: number; y: number; w: number; h: number};
export const COVER_AVATAR_D: number;
export const COVER_AVATAR: {x: number; y: number; w: number; h: number};
export const COVER_MORPH_MS: number;
export const TURN_OUT_MS: number;
export const TURN_IN_DELAY_MS: number;
export const TURN_IN_MS: number;
export const TURN_SHIFT_PX: number;
export const TURN_MAX_OVERLAP: number;
export function pageTurnAt(tMs: number): {outgoing: {opacity: number; dy: number}; incoming: {opacity: number; dy: number}};
export function contentMotion(input?: {first?: boolean; inTail?: boolean; tMs?: number}): {opacity: number; dy: number};
export function turnOutFrames(fps?: number): number;
export function contentBlankMs(fps?: number): number;
export function chapterLineKey(page: {layout?: string; index?: number; chapterIndex?: number; chapterTitle?: string} | null | undefined, options?: {brandRecapIndex?: number | null}): string | null;
export function sameChapterLine(a: {layout?: string; index?: number; chapterIndex?: number; chapterTitle?: string} | null | undefined, b: {layout?: string; index?: number; chapterIndex?: number; chapterTitle?: string} | null | undefined, options?: {brandRecapIndex?: number | null}): boolean;
export function chapterLineOpacity(input?: {sameChapter?: boolean; role?: string; tMs?: number}): number;
export function chapterLineMode(input?: {key?: string | null; first?: boolean; inTail?: boolean; holdPrev?: boolean; holdNext?: boolean; tMs?: number}): 'none' | 'stable' | 'turn';
export const BUG_OFFSET: number;
export const BUG: {left: number; top: number; logo: number; gap: number; font: number; tracking: number};
export const NAMEBAR_TOTAL_MS: number;
export const NAMEBAR_SLIDE_MS: number;
export const NAMEBAR: {right: number; bottom: number};
export function headerShift(withBug?: boolean): number;
export function nameBarSlide(localMs: number, pageMs: number): {visible: boolean; x: number; opacity: number};

export const SUBTITLE: {
  centerX: number;
  maxWidth: number;
  bottom: number;
  fontPx: number;
  minFont: number;
  padX: number;
  padY: number;
  radius: number;
  lineHeight: number;
  color: string;
  background: string;
};

export type StageBox = {x: number; y: number; width: number; height: number};
export const STAGE: {standard: StageBox; wide: StageBox; tall: StageBox; side: StageBox; cover: StageBox};
export const LAYOUT_NAMES: string[];
export function contentFrame(layout: string): StageBox;
export const RESERVE_ROW_RIGHT: number;
export function nameBarMetrics(input?: {name?: string; title?: string; firmLine?: string}): {x: number; y: number; width: number; height: number; right: number; bottom: number};
export function nameBarReserve(metrics: {x: number; y: number}): {x: number; y: number};
export function intersectsReserve(box: {x: number; y: number; w?: number; h?: number; width?: number; height?: number}, reserve?: {x: number; y: number}): boolean;
export function insideContent(box: {x: number; y: number; w?: number; h?: number; width?: number; height?: number}): boolean;
export function fitBlockFont(input: {chars: number; width: number; maxFont: number; lineHeight: number; maxHeight: number; minFont?: number}): number;
export function titleFontPx(text: string, width?: number): number;
export function subtitleLayout(text: string): {x: number; y: number; width: number; height: number; font: number; lines: string[]; lineHeight: number};
export function quoteBlockSize(quote: string, source: string, options?: {width?: number; tag?: boolean}): {width: number; inner: number; sourceH: number; quoteH: number; tagH: number; height: number};
export function longestCopy(layout: string): Record<string, number | string>;
export const TYPE: {
  quote: number; quoteSource: number; quoteTag: number;
  pointsTitle: number; pointsBody: number; pointsIndex: number; pointsIcon: number;
  statement: number; statementBasis: number; propTitle: number; propLine: number;
  compareTitle: number; compareVerdict: number; compareIcon: number;
  flowTitle: number; flowPoint: number; flowIcon: number;
  timelineNode: number; timelineSeg: number; timelineQuote: number;
  checkItem: number; checkBox: number; checkIndex: number; checkNum: number;
  bigNumber: number; bigUnit: number; bigName: number; bigCard: number;
  saying: number; sayingName: number; sayingOrg: number;
  levelsText: number; levelsIcon: number;
  questionOption: number; questionLetter: number;
  caseBubble: number; caseFace: number; caseVerdict: number;
  documentAmount: number; documentPoint: number; documentZoom: number;
  tableHead: number; tableSituation: number; tableResult: number; tableBasis: number;
  chapterNum: number; chapterTitle: number; chapterPoint: number;
  recapHead: number; recapItem: number; recapIndex: number;
  stepsBody: number;
};
export function boxTextFits(box: {text?: string; w: number; h: number; fontPx: number; lineHeight?: number}): boolean;
export function layoutContentBoxes(layout: string, options?: {reserve?: {x: number; y: number}}): Array<{x: number; y: number; w: number; h: number; fontPx: number; text?: string; lineHeight?: number; bleed?: boolean}>;
